apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: kingerit/calculator:latest
          ports:
            - containerPort: 8080
